CI: add compile tests
Eideticom/eid-hermes-qemu pull request #16
Opened 2021-05-03 17:25 UTC by iomartin

Make sure that the project compiles.

2021-05-03 18:09 UTC, sbates130272 requested changes

2021-05-03 18:09 UTC, sbates130272 commented on .github/workflows/compile.yml
> +       - name: Install uBPF
Do we want to lock this to a tag of ubpf?

2021-05-03 18:09 UTC, sbates130272 commented on .github/workflows/compile.yml
> +on: [push, pull_request]
I don't think we want this on pushes to dev branches as they are often broken. I normally do this on PR against master and then also make it part of the master branch rules.

2021-05-03 22:15 UTC, iomartin commented
@sbates130272, I fixed the code to address your comments.

I was getting some timeouts when running the CI and it turns out it was a bandwidth issue on where some of the git modules are hosted. So I cherry-picked a commit from upstream that changes the address of those modules and I added to this PR as well.

2021-05-04 01:17 UTC, sbates130272 approved these changes
Thanks @iomartin. Looks good!

2021-05-04 01:18 UTC, merged