Dockerfile-hermes: Add Dockerfile for eid-hermes project
Eideticom/eid-hermes-qemu pull request #3
Opened 2020-10-08 22:24 UTC by sbates130272

Add a Dockerfile that pulls the Eideticom QEMU repo and builds the x86
system emulator. It uses a rootfs for this VM that is generated using
gen-images (using cloud-init) and spins the whole thing up.

Note that in order for this Dockerfile to work you need to put some
SSH keys into the docker/hermes folder and ensure the Ubunutu focal
cloud image is also in that folder. This requirement may go away once
we open this project to the public.

Note that the cloud-init networking should allow for instance SSH into
the VM via port 2222. The username and password for the main account
on the VM is 'hermes' and 'zeus'. Note we add a .dockerignore to avoid
pulling the large images into context. We also include a
docker-compose.yml for easier management and a README.md to summarize
this approach.

2020-10-10 00:19 UTC, iomartin requested changes
Looks mostly good, just some minor comments

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/gen-images
> +  - emacs-nox
Can you add ansible as well?

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/gen-images
> +   wget https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
We should put this on the images directory

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/Dockerfile
> +  # it. Pass in this SHA as an argument.
nit: whitespace at the end of line

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/Dockerfile
> +
nit: whitespace on empty line

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/README.md
> +4. ```ssh -v -p 2222 hermes@localhost``` - note you might have to redo
We don't need the -v

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/Dockerfile
> +  git fetch eid && \
We could do

    git fetch eid $HERMES_QEMU_SHA --depth=1

to limit the amount of data that we need to pull

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/.gitignore
> +focal-server-cloudimg-amd64.img
We should add `id_rsa` here as well

2020-10-10 00:19 UTC, iomartin commented on docker/hermes/docker-compose.yml
> +        HERMES_QEMU_SHA: 421feca1573f3b25b0c89d11752c7a7d0cd91f81
Let's remember to update this before we merge

2020-10-14 17:06 UTC, sbates130272 commented on docker/hermes/Dockerfile
> +  git fetch eid && \
@iomartin I changed this a bit. I moved the _SHA to _REF and now the default is the HEAD of the hermes branch. This allows a user to put a branch or a commit SHA in the docker-compose file. I also updated the README to inform users they can alter this in docker-compose to test other branches and commits.

2020-10-14 17:06 UTC, sbates130272 commented on docker/hermes/Dockerfile
> +  git fetch eid && \
Oh except the head of hermes branch is broken until we get the libubpf code in. So I will change it to the head of your branch for now.

2020-10-14 17:53 UTC, iomartin requested changes

2020-10-14 17:53 UTC, iomartin commented on docker/hermes/Dockerfile
> +  git fetch eid && \
With _REF we should still be able to use --depth=1. We just needs to drop the `-b` on the checkout:

```
git fetch eid $HERMES_QEMU_REF --depth=1 && \
git checkout $HERMES_QEMU_REF
```

Also, if REF is a branch, then it should not have the `eid/` prefix for this to work

2020-10-14 17:53 UTC, iomartin commented on docker/hermes/README.md
> +to point to the commit REF you care about. Do this in
s/commit REF/commit REF or branch/

2020-10-14 17:53 UTC, iomartin commented on docker/hermes/gen-images
> +mkdir -p ${DIR}
The mkdir has to be before the previous if

2020-10-14 17:53 UTC, iomartin commented on docker/hermes/docker-compose.yml
> +        HERMES_QEMU_REF: eid/martin/hermes_v3
see comment about git fetch

2020-10-14 18:09 UTC, sbates130272 commented on docker/hermes/Dockerfile
> +  git fetch eid && \
@iomartin I thought this failed for me. But it looks like it works so I will do this.

2020-10-14 18:10 UTC, sbates130272 commented on docker/hermes/docker-compose.yml
> +        HERMES_QEMU_SHA: 421feca1573f3b25b0c89d11752c7a7d0cd91f81
Now set to martin/hermes_v3. We can update to hermes once your PR is merged.

2020-10-14 21:36 UTC, iomartin approved these changes

2020-10-14 21:55 UTC, merged